version: '3.9'

services:
  app:
    container_name: app
    image: marcelofabianov/rust-dev
    restart: always
    working_dir: /workspace
    build:
      context: ./_docker
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/workspace
      - ./_docker/.zshrc:/home/dev/.zshrc
      - ./_docker/.zsh_history:/home/dev/.zsh_history
    ports:
      - "8888:8888"
    networks:
      - rust_network

networks:
  rust_network:
    driver: bridge
